paths-ignore:                                                                                                                                                                                       
    - 'src/resources/pii-test-corpus.json'
    - 'dist/resources/pii-test-corpus.json'
